"""Request and response schemas for the Book resource."""

from pydantic import BaseModel, ConfigDict, Field
from datetime import datetime


class Book(BaseModel):
    """Define fields shared by every Book schema."""
    
    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
    )
    title: str = Field(
        min_length=1, 
        max_length=200,
        description="Book Title"
        )
    author: str = Field(
        min_length=1,
        max_length=200,
        description="Book Author"
    )
    isbn: str = Field(
        description="Unique ISBN"
    )
    published_year: int = Field(
        ge=1450,
        le=2026,
        description="Year the book was published"
    )
    member_id: int = Field(
        gt=0, 
        description="ID of the member who borrowed this book"
    )


class BookRequest(Book):
    """Validate client-controlled fields for a Book create or update."""


class BookResponse(Book):
    """Describe a Book returned by the API."""

    # The server generates the ID, so it appears in response but not in
    # BookRequest request bodies.
    id: int = Field(
        gt=0,
        description="Unique identifier generated by the server.",
        examples=[1]
    )