"""Request and response schema for the Member resource."""


from pydantic import BaseModel, ConfigDict, Field, EmailStr


class Member(BaseModel):
    """Define fields shared by every Task schema."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True
    )
    name: str = Field(
        min_length=1,
        max_length=120,
        description="Member Name"
    )
    email: EmailStr = Field(
        description="Member email address (must be unique)"
    )
    membership_id: str = Field(
        description="Member membership ID (must be unique)"
    )
    phone: str = Field(
        pattern=r"^\d{3}-\d{3}-\d{4}$",
        description="Member phone number (format: xxx-XXX-XXXX, e.g., 555-123-4567)"
    )

class MemberRequest(Member):
    """Validate client-controlled fields for a Member create or update."""


class MemberResponse(Member):
    """Describe a Member returned by the API."""

    id: int = Field(
        gt=0,
        description="Unique identifier generated by the server.",
        examples=[1]
    )